gan_config:
  dp: true
  dataset:
    name: cifar10
    params: {}
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: true
  generator:
    name: MMCDCGenerator
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/CIFAR10/DCGAN_NS/netG_100000_steps.pth
  discriminator:
    name: MMCDCDiscriminator
    params:
      mean: *mean
      std: *std
      output_layer: identity
    ckpt_path: checkpoints/CIFAR10/DCGAN_NS/netD_100000_steps.pth
