sampling: &sampling ula
mcmc_args: &mcmc_args
  n_samples: 1
  burn_in: 0
dir: &dir log
n_steps: &n_steps 1000
every: &every 50
seed:
device: &device cuda
burn_in_steps: &burn_in_steps 0.0
start_sample: &start_sample 0.0
total_n: &total_n 10000
batch_size: &batch_size 180
data_batch_size: *batch_size
step_size: &step_size 0.01
name: &name mmc_dcgan
sub_dir: &sub_dir mmc_dcgan
suffix: *step_size
gan_config:
  dp: true
  dataset:
    name: cifar10
    params: {}
  train_transform:
    Normalize:
      mean: &mean [0.5, 0.5, 0.5]
      std: &std [0.5, 0.5, 0.5]
  prior: normal
  eval: true
  generator:
    name: MMCDCGenerator
    params:
      mean: *mean
      std: *std
    ckpt_path: checkpoints/CIFAR10/DCGAN_NS/netG_100000_steps.pth
  discriminator:
    name: MMCDCDiscriminator
    params:
      mean: *mean
      std: *std
      output_layer: identity
    ckpt_path: checkpoints/CIFAR10/DCGAN_NS/netD_100000_steps.pth
distribution: &target_distribution
  name: DiscriminatorTarget
sample_params: &sample_params
  sample: true
  save_dir: *dir
  sub_dir: *sub_dir
  distribution:
    <<: *target_distribution
  total_n: *total_n
  batch_size: *batch_size
  save_every: *every
  params:
    n_steps: *n_steps
    save_every: *every
    burn_in_steps: *burn_in_steps
    start_sample: *start_sample
    n_sampling_steps: &n_sampling_steps 1
    sampling: *sampling
    mcmc_args:
      <<: *mcmc_args
      step_size: *step_size
afterall_params:
  results_dir: *dir
  sub_dir: *sub_dir
  init_wandb: true
  compute_is: true
  compute_fid: true
  save_chains: true
params:
  sample_params: *sample_params
  name: *name
  feature:
    name: discriminator
wandb_init_params:
logging:
  wandb:
callbacks:
  # feature_callbacks: &feature_callbacks
  #   log_weight:
  #     name: LogCallback
  #     params:
  #       invoke_every: *every
  #       keys:
  #         - weight_norm
  #       save_dir: null
  #   log_out:
  #     name: LogCallback
  #     params:
  #       invoke_every: *every
  #       keys:
  #         - out
  #       save_dir: null
  #   log_ref:
  #     name: LogCallback
  #     params:
  #       invoke_every: *every
  #       keys:
  #         - ref_score
  #       save_dir: null
  #   log_res:
  #     name: LogCallback
  #     params:
  #       invoke_every: *every
  #       keys:
  #         - residual
  #       save_dir: null
  #   energy:
  #     name: EnergyCallback
  #     params:
  #       gan: null
  #       invoke_every: *every
  #       device: *device
  #       update_input: true
  #       # batch_size: *batch_size
  #       norm_constant: null
  #   log_energy:
  #     name: LogCallback
  #     params:
  #       invoke_every: *every
  #       keys:
  #         - Energy
  #       save_dir: null
  #   log_dot_pr:
  #     name: LogCallback
  #     params:
  #       invoke_every: *every
  #       keys:
  #         - dot_pr
  #       save_dir: null

  sampler_callbacks:
    log_step_size:
      name: LogCallback
      params:
        invoke_every: *every
        keys:
        - step_size
        save_dir:
  afterall_callbacks:
    energy:
      name: EnergyCallback
      params:
        gan:
        invoke_every: 1
        device: *device
        update_input: true
        batch_size: *batch_size
        norm_constant:
    discriminator:
      name: DiscriminatorCallback
      params:
        gan:
        invoke_every: 1
        device: *device
        update_input: true
        batch_size: *batch_size
